import os
from strands import tool
from google import genai
from google.genai import types
from influencerpy.config import ConfigManager

@tool
def google_search(query: str) -> str:
    """
    Perform a Google Search using Gemini Grounding.
    
    Use this tool to find real-time information, news, and updates from the web.
    
    Args:
        query: The search query string.
        
    Returns:
        The search result summary generated by Gemini.
    """
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        return "Error: GEMINI_API_KEY not found."
        
    config_manager = ConfigManager()
    model_id = config_manager.get("ai.search.model", "gemini-2.5-flash")
    
    try:
        client = genai.Client(api_key=api_key)
        
        grounding_tool = types.Tool(
            google_search=types.GoogleSearch()
        )
        
        config = types.GenerateContentConfig(
            tools=[grounding_tool]
        )
        
        # Enhanced prompt to get more detailed results
        enhanced_query = f"""
        Perform a comprehensive search on: {query}
        
        Provide a detailed summary of the search results.
        Focus on:
        1. Key facts and latest updates.
        2. Important context or background information.
        3. Specific details (dates, names, numbers).
        4. Different perspectives or analysis found in the results.
        
        Aim for a substantial summary (at least 3-4 paragraphs) that gives a complete picture of the topic.
        """
        
        response = client.models.generate_content(
            model=model_id,
            contents=enhanced_query,
            config=config,
        )
        
        result_text = response.text
        
        # Extract sources from grounding metadata
        sources = []
        if response.candidates and response.candidates[0].grounding_metadata:
            metadata = response.candidates[0].grounding_metadata
            if metadata.grounding_chunks:
                for chunk in metadata.grounding_chunks:
                    if chunk.web:
                        title = chunk.web.title or "Unknown Source"
                        uri = chunk.web.uri or "#"
                        sources.append(f"- {title}: {uri}")
        
        # Deduplicate and append sources
        if sources:
            unique_sources = list(set(sources))
            result_text += "\n\n**Sources:**\n" + "\n".join(unique_sources)
            
        return result_text
    except Exception as e:
        return f"Error performing search: {e}"
